/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeagueRouteImport } from './routes/$league'
import { Route as LeagueIndexRouteImport } from './routes/$league.index'
import { Route as LeagueCompareRouteImport } from './routes/$league.compare'
import { Route as LeagueFavoritesRouteImport } from './routes/$league.favorites'
import { Route as LeagueLeadersRouteImport } from './routes/$league.leaders'
import { Route as LeagueStandingsRouteImport } from './routes/$league.standings'
import { Route as LeagueGameGameIdRouteImport } from './routes/$league.game.$gameId'
import { Route as LeaguePlayerPlayerIdRouteImport } from './routes/$league.player.$playerId'
import { Route as LeagueTeamsIndexRouteImport } from './routes/$league.teams.index'
import { Route as LeagueTeamsTeamIdRouteImport } from './routes/$league.teams.$teamId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueRoute = LeagueRouteImport.update({
  id: '/$league',
  path: '/$league',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueIndexRoute = LeagueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeagueRoute,
} as any)
const LeagueCompareRoute = LeagueCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => LeagueRoute,
} as any)
const LeagueFavoritesRoute = LeagueFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => LeagueRoute,
} as any)
const LeagueLeadersRoute = LeagueLeadersRouteImport.update({
  id: '/leaders',
  path: '/leaders',
  getParentRoute: () => LeagueRoute,
} as any)
const LeagueStandingsRoute = LeagueStandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => LeagueRoute,
} as any)
const LeagueGameGameIdRoute = LeagueGameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => LeagueRoute,
} as any)
const LeaguePlayerPlayerIdRoute = LeaguePlayerPlayerIdRouteImport.update({
  id: '/player/$playerId',
  path: '/player/$playerId',
  getParentRoute: () => LeagueRoute,
} as any)
const LeagueTeamsIndexRoute = LeagueTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => LeagueRoute,
} as any)
const LeagueTeamsTeamIdRoute = LeagueTeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => LeagueRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$league': typeof LeagueRouteWithChildren
  '/$league/compare': typeof LeagueCompareRoute
  '/$league/favorites': typeof LeagueFavoritesRoute
  '/$league/leaders': typeof LeagueLeadersRoute
  '/$league/standings': typeof LeagueStandingsRoute
  '/$league/': typeof LeagueIndexRoute
  '/$league/game/$gameId': typeof LeagueGameGameIdRoute
  '/$league/player/$playerId': typeof LeaguePlayerPlayerIdRoute
  '/$league/teams/$teamId': typeof LeagueTeamsTeamIdRoute
  '/$league/teams/': typeof LeagueTeamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$league/compare': typeof LeagueCompareRoute
  '/$league/favorites': typeof LeagueFavoritesRoute
  '/$league/leaders': typeof LeagueLeadersRoute
  '/$league/standings': typeof LeagueStandingsRoute
  '/$league': typeof LeagueIndexRoute
  '/$league/game/$gameId': typeof LeagueGameGameIdRoute
  '/$league/player/$playerId': typeof LeaguePlayerPlayerIdRoute
  '/$league/teams/$teamId': typeof LeagueTeamsTeamIdRoute
  '/$league/teams': typeof LeagueTeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$league': typeof LeagueRouteWithChildren
  '/$league/compare': typeof LeagueCompareRoute
  '/$league/favorites': typeof LeagueFavoritesRoute
  '/$league/leaders': typeof LeagueLeadersRoute
  '/$league/standings': typeof LeagueStandingsRoute
  '/$league/': typeof LeagueIndexRoute
  '/$league/game/$gameId': typeof LeagueGameGameIdRoute
  '/$league/player/$playerId': typeof LeaguePlayerPlayerIdRoute
  '/$league/teams/$teamId': typeof LeagueTeamsTeamIdRoute
  '/$league/teams/': typeof LeagueTeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$league'
    | '/$league/compare'
    | '/$league/favorites'
    | '/$league/leaders'
    | '/$league/standings'
    | '/$league/'
    | '/$league/game/$gameId'
    | '/$league/player/$playerId'
    | '/$league/teams/$teamId'
    | '/$league/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$league/compare'
    | '/$league/favorites'
    | '/$league/leaders'
    | '/$league/standings'
    | '/$league'
    | '/$league/game/$gameId'
    | '/$league/player/$playerId'
    | '/$league/teams/$teamId'
    | '/$league/teams'
  id:
    | '__root__'
    | '/'
    | '/$league'
    | '/$league/compare'
    | '/$league/favorites'
    | '/$league/leaders'
    | '/$league/standings'
    | '/$league/'
    | '/$league/game/$gameId'
    | '/$league/player/$playerId'
    | '/$league/teams/$teamId'
    | '/$league/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeagueRoute: typeof LeagueRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$league': {
      id: '/$league'
      path: '/$league'
      fullPath: '/$league'
      preLoaderRoute: typeof LeagueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$league/': {
      id: '/$league/'
      path: '/'
      fullPath: '/$league/'
      preLoaderRoute: typeof LeagueIndexRouteImport
      parentRoute: typeof LeagueRoute
    }
    '/$league/compare': {
      id: '/$league/compare'
      path: '/compare'
      fullPath: '/$league/compare'
      preLoaderRoute: typeof LeagueCompareRouteImport
      parentRoute: typeof LeagueRoute
    }
    '/$league/favorites': {
      id: '/$league/favorites'
      path: '/favorites'
      fullPath: '/$league/favorites'
      preLoaderRoute: typeof LeagueFavoritesRouteImport
      parentRoute: typeof LeagueRoute
    }
    '/$league/leaders': {
      id: '/$league/leaders'
      path: '/leaders'
      fullPath: '/$league/leaders'
      preLoaderRoute: typeof LeagueLeadersRouteImport
      parentRoute: typeof LeagueRoute
    }
    '/$league/standings': {
      id: '/$league/standings'
      path: '/standings'
      fullPath: '/$league/standings'
      preLoaderRoute: typeof LeagueStandingsRouteImport
      parentRoute: typeof LeagueRoute
    }
    '/$league/game/$gameId': {
      id: '/$league/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/$league/game/$gameId'
      preLoaderRoute: typeof LeagueGameGameIdRouteImport
      parentRoute: typeof LeagueRoute
    }
    '/$league/player/$playerId': {
      id: '/$league/player/$playerId'
      path: '/player/$playerId'
      fullPath: '/$league/player/$playerId'
      preLoaderRoute: typeof LeaguePlayerPlayerIdRouteImport
      parentRoute: typeof LeagueRoute
    }
    '/$league/teams/': {
      id: '/$league/teams/'
      path: '/teams'
      fullPath: '/$league/teams/'
      preLoaderRoute: typeof LeagueTeamsIndexRouteImport
      parentRoute: typeof LeagueRoute
    }
    '/$league/teams/$teamId': {
      id: '/$league/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/$league/teams/$teamId'
      preLoaderRoute: typeof LeagueTeamsTeamIdRouteImport
      parentRoute: typeof LeagueRoute
    }
  }
}

interface LeagueRouteChildren {
  LeagueCompareRoute: typeof LeagueCompareRoute
  LeagueFavoritesRoute: typeof LeagueFavoritesRoute
  LeagueLeadersRoute: typeof LeagueLeadersRoute
  LeagueStandingsRoute: typeof LeagueStandingsRoute
  LeagueIndexRoute: typeof LeagueIndexRoute
  LeagueGameGameIdRoute: typeof LeagueGameGameIdRoute
  LeaguePlayerPlayerIdRoute: typeof LeaguePlayerPlayerIdRoute
  LeagueTeamsTeamIdRoute: typeof LeagueTeamsTeamIdRoute
  LeagueTeamsIndexRoute: typeof LeagueTeamsIndexRoute
}

const LeagueRouteChildren: LeagueRouteChildren = {
  LeagueCompareRoute: LeagueCompareRoute,
  LeagueFavoritesRoute: LeagueFavoritesRoute,
  LeagueLeadersRoute: LeagueLeadersRoute,
  LeagueStandingsRoute: LeagueStandingsRoute,
  LeagueIndexRoute: LeagueIndexRoute,
  LeagueGameGameIdRoute: LeagueGameGameIdRoute,
  LeaguePlayerPlayerIdRoute: LeaguePlayerPlayerIdRoute,
  LeagueTeamsTeamIdRoute: LeagueTeamsTeamIdRoute,
  LeagueTeamsIndexRoute: LeagueTeamsIndexRoute,
}

const LeagueRouteWithChildren =
  LeagueRoute._addFileChildren(LeagueRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeagueRoute: LeagueRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
